Detego.CatWalk.Web/Models/DayReportParameters.cs
using System;

namespace Detego.CatWalk.Web.Models
{
    public class DayReportParameters
    {
        public int SiteId { get; set; }

        public DateTime Date { get; set; }
    }
}

Detego.CatWalk.Web/Models/StockTakeInfo.cs
using System.Collections.Generic;

namespace Detego.CatWalk.Web.Models
{
    public class StockTakeInfo
    {
        public string Site { get; set; }

        public string Location { get; set; }

        public string Readpoint { get; set; }

        public string User { get; set; }

        public List<string> EpcList { get; set; }

        public int TimeZone { get; set; }
    }
}

Detego.CatWalk.Web/Controllers/AdminController.cs
using System.Web.Mvc;

namespace Detego.CatWalk.Web.Controllers
{
    public class AdminController : Controller
    {  
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Import()
        {
            return View();
        }
    }
}

Detego.CatWalk.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Detego.CatWalk.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Detego.CatWalk.Web/Controllers/LoginController.cs
using System;
using System.Web.Mvc;

namespace Detego.CatWalk.Web.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangePassword(string email, string token)
        {           
            return View(Tuple.Create(email, token));
        }
    }
}

Detego.CatWalk.Web/Controllers/StockTakesController.cs
using System;
using System.Web.Mvc;
using Detego.CatWalk.Web.Models;

namespace Detego.CatWalk.Web.Controllers
{
    public class StockTakesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Report(int id)
        {
            return View(id);
        }

        [Route("Stocktakes/Report/{id}/{date}")]
        public ActionResult DayReport(int id, DateTime date)
        {
            return View(new DayReportParameters { SiteId = id, Date = date });
        }
    }
}

Detego.CatWalk.Web/Views/Login/ChangePassword.cshtml
@model Tuple<string, string>

@{
    ViewBag.Title = "Change Password";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h2>Change password for @Model.Item1</h2>
<div class="demo-section k-content">
    <div id="error" style="display: none; color: red"></div>
    <div>
        <div>
            <label>New Password:</label>
        </div>
        <input class="k-textbox" type="password" id="password" value=""/>
        <div>
            <p>
                <button id="change" class="k-button k-primary">Change Password</button>
            </p>
        </div>
    </div>
</div>

<script>
    SiteUrl = '@(string.Concat(Request.Url.GetLeftPart(UriPartial.Authority), Request.ApplicationPath))';
    function checkPassword(password) {
        if (password.length != 8)
            return false;
        return (/\d/.test(password));
    }

    $(document).ready(function () {
        $("#change").click(function (e) {
            if (checkPassword($("#password").val())) {
                $("#error").hide();
                $.ajax({
                    type: "POST",
                    url: ApiBaseUrl + "Login/ChangePassword",
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    data: JSON.stringify({
                        Email: '@Model.Item1',
                        Token: '@Model.Item2',
                        NewPassword: $("#password").val()
                    }),
                    beforeSend: function() {                    
                    },
                    success: function (result) {
                        window.location.href = "@Url.Action("Index", "Login", null, Request.Url.Scheme)";
                    },
                    error: function (result) {
                        window.location.href = "@Url.Action("Index", "Login", null, Request.Url.Scheme)";
                    }
                });
            } else {
                $("#error").text("Password should be 8 characters with 1 number minimum");
                $("#error").show();
            }
        });
    });
</script>
<style>
    .demo-section p {
        margin: 0 0 10px;
        line-height: 50px;
    }
</style>

Detego.CatWalk.Web/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h2>Login</h2>
<div class="box wide">
    <div id="loading"></div>
    <div class="demo-section k-content">
        <div id="error" style="display: none; color: red"></div>
        <div id="loginPanel">
            <div>
                <label>Email:</label>
            </div>
            <div>
                <input class="k-textbox" type="email" id="email" value="" required data-email-msg="Email format is not valid" />
            </div>
            <div>
                <label>Password:</label>
            </div>
            <div>
                <input class="k-textbox" type="password" id="password" required value="" />
            </div>
            <div>
                <p>
                    <button id="login" class="k-button k-primary">Login</button>
                </p>
            </div>
            <div>
                <a id="forgot" href="">Forgot your password?</a>
            </div>
        </div>
        <div id="forgotPanel" style="display: none">
            <div>Please enter your email address below and you will receive an email with instructions on how to reset your password:</div>
            <div>
                <label>Email:</label>
            </div>
            <input class="k-textbox" type="email" id="email2" value="" required data-email-msg="Email format is not valid" />
            <div>
                <p>
                    <button id="reset" class="k-button k-primary">Reset password</button>
                    <button id="cancel" class="k-button k-primary">Cancel</button>
                </p>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#forgotPanel").hide();
        clearUserData();

        $("#login").click(function(e) {
            var valid = true;

            $('input:visible').each(function(i, v) {
                if ($(this).prop('required') && $(this).val().trim() == "") {
                    valid = false;
                }
            });

            if (valid) {
                var authString = "Bsc " + btoa($("#email").val() + ":" + $("#password").val());
                saveAuth(authString);
                kendo.ui.progress($("#loading"), true);

                $.ajax({
                    method: "GET",
                    url: ApiBaseUrl + "Login",
                    beforeSend: function(xhr) {
                        xhr.setRequestHeader("Authorization", authString);
                    },
                    success: function(result) {
                        kendo.ui.progress($("#loading"), false);

                        if (result != "") {
                            var token = result.replace(/"/g, '');
                            window.location.href = '@Url.Action("ChangePassword", "Login", null, Request.Url.Scheme)' + '?email=' + $("#email").val() + '&token=' + token;
                        } else {
                            saveEmail($("#email").val());

                            var role = getUserRole2(function() {
                                role = getUserRole();

                                if (role == "Root Account" || role == "IT Admin")
                                    window.location.href = "@Url.Action("Index", "Home", null, Request.Url.Scheme)";
                                else
                                    window.location.href = "@Url.Action("Index", "StockTakes", null, Request.Url.Scheme)";
                            });
                        }
                    },
                    failure: function() {
                        kendo.ui.progress($("#loading"), false);
                        alert("failure");
                    },
                    error: function(a, b, c) {
                        kendo.ui.progress($("#loading"), false);
                        $("#error").text(a.responseText);
                        $("#error").show();
                        clearUserData();
                    }
                });
            } else {
                $("#error").text("Email and password required.");
                $("#error").show();
            }
        });

        $("#forgot").click(function(e) {
            e.preventDefault();
            $("#loginPanel").hide();
            $("#forgotPanel").show();
            $("#error").hide();
        });

        $("#cancel").click(function() {
            $("#loginPanel").show();
            $("#forgotPanel").hide();
        });

        $("#reset").click(function () {
            var siteUrl = "@(string.Concat(Request.Url.GetLeftPart(UriPartial.Authority), Request.ApplicationPath))";
            if (siteUrl.slice(-1) != '/')
                siteUrl += '/';
            $.ajax({
                url: ApiBaseUrl + "Login/ResetPassword?url=" + siteUrl + "/Login&email=" + $("#email2").val(),
                method: "GET",
                beforeSend: function () {
                },
                success: function() {
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#error").text(jqXHR.responseText);
                    $("#error").show();
                }
              });


            $("#loginPanel").show();
            $("#forgotPanel").hide();
        });
    });
</script>
<style>
.demo-section p {
    margin: 0 0 10px;
    line-height: 50px;
}
.demo-section p .k-button {
    margin: 0 10px 0 0;
}
</style>

Detego.CatWalk.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="detego Surveyor">
    <meta name="author" content="Enso Detego GmbH">
    <meta name="accept-language" content="en-US"/>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.default.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.default.mobile.min.css"/>
    <script src="https://kendo.cdn.telerik.com/2016.2.504/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2016.2.504/js/kendo.all.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/scripts")

    <script> 
        SiteUrl = '@(string.Concat(Request.Url.GetLeftPart(UriPartial.Authority), Request.ApplicationPath))';
        checkVisit();
    </script>

    <link rel="shortcut icon" href="~/Content/Images/EDG_Favicon_4c_pos.ico" type="image/x-icon" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/Images/EDG_Favicon_4c_pos_144.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/Images/EDG_Favicon_4c_pos_72.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/Images/EEDG_Favicon_4c_pos_57.png">
</head>
<body>
<div>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/Content/Images/EDG-R_Logo_4c_pos.svg" alt="DETEGO" width="252" height="50" />
                <span class="navbar-brand-text">SUITE</span>
            </a>
            
            <div class="collapse navbar-collapse" id="navbar-collapse-navs">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href=@Url.Action("Index", "Home") data-bind="click: navigate" id="HomeLink">Home</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Index", "Admin") data-bind="click: navigate" id="AdminLink">Administration</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Import", "Admin") data-bind="click: navigate" id="ImportLink">Import Master Data</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Index", "StockTakes") data-bind="click: navigate">Stocktakes</a>
                    </li>
                    <li>
                        <a href=@Url.Action("Index", "Login") data-bind="click: navigate" id="Login">Login</a>
                    </li>
                    <li>
                        <a class="label" id="HelloLabel"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>
</div>
<script>
    $(document).ready(function () {
        if (checkLogged()) {
            $("#Login").text("Logout");
            $("#HelloLabel").text("Logged as: " + getEmail());

            var role = getUserRole();
            if (role != "Root Account" && role != "IT Admin") {
                $("#ImportLink").hide();
                $("#HomeLink").hide();
                $("a.navbar-brand").attr("href", "@Url.Action("Index", "StockTakes")");
            }
            if (role == "User Account")
                $("#AdminLink").hide();
        } else {
            $("#Login").text("Login");
        }

        $("#Login").click(function() {
            clearUserData();
        });
    });
</script>
</body>
</html>

Detego.CatWalk.Web/Views/Shared/_LoginLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="detego Surveyor">
    <meta name="author" content="Enso Detego GmbH">
    <meta name="accept-language" content="en-US">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.default.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.2.504/styles/kendo.default.mobile.min.css" />
    <script src="https://kendo.cdn.telerik.com/2016.2.504/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2016.2.504/js/kendo.all.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/scripts")

    <link rel="shortcut icon" href="~/Content/Images/EDG_Favicon_4c_pos.ico" type="image/x-icon" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/Images/EDG_Favicon_4c_pos_144.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/Images/EDG_Favicon_4c_pos_72.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/Images/EEDG_Favicon_4c_pos_57.png">
</head>
<body>
    <div>
        <nav class="navbar navbar-default navbar-inverse" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="~/Content/Images/EDG-R_Logo_4c_pos.svg" alt="DETEGO" width="252" height="50" />
                    <span class="navbar-brand-text">SUITE</span>
                </a>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year</p>
            </footer>
        </div>
    </div>
</body>
</html>

Detego.CatWalk.Web/Views/StockTakes/DayReport.cshtml
@model Detego.CatWalk.Web.Models.DayReportParameters

@{
    ViewBag.Title = "Daily Report";
}

<h2>Report for @Model.Date.ToString("MM-dd-yyyy")</h2>

<button id="export" class="k-button">Export to CSV</button>
<div class="k-content">
    <div id="loading"></div>
    <div id="grid"></div>
</div>
<script>
    $(document).ready(function() {
        var fields;
        var myColumns = [];
        var values = [];
        var data = [];
        kendo.ui.progress($("#loading"), true);

        $.ajax({
            url: ApiBaseUrl + "Reports/" + @Model.SiteId + '/@Model.Date.ToString("MM-dd-yyyy")/',
            dataType: "json",
            success: function(result) {
                if (result != null) {
                    values = result.Rows;
                    fields = result.Columns;
                    for (var i = 0; i < fields.length; i++) {
                        if (i == 0) {
                            myColumns.push({ template: "<img src='#= Image #'  height=64 width=64 />", field: fields[i].replace(/\s/g, ''), title: fields[i], width: '75px', filterable: false });
                        } else {
                            if (fields[i].replace(/\s/g, '').toLowerCase() == "gtin" || fields[i].replace(/\s/g, '').toLowerCase() == "upc" || fields[i].replace(/\s/g, '').toLowerCase() == "articlenumber")
                                myColumns.push({
                                    field: fields[i].replace(/\s/g, ''),
                                    title: fields[i],
                                    width: '150px',
                                    filterable: {
                                        cell: {
                                            operator: "contains"
                                        }
                                    }
                                });
                            else
                                myColumns.push({ field: '["' + fields[i].replace(/\s/g, '') + '"]', title: fields[i], width: '75px', filterable: false });
                        }
                    }
                    for (var i = 0; i < result.Rows.length; i++) {
                        var obj = {};
                        for (var j = 0; j < result.Rows[i].length; j++)
                            obj[fields[j].replace(/\s/g, '')] = result.Rows[i][j];
                        data.push(obj);
                    }
                    var ca = document.cookie.split(';');
                    var dsSort = [];
                    for (var i = 0; i < ca.length; i++) {
                        var c = ca[i];
                        if (c.substring(0, 9) == ' grouping' && c.substring(10, c.indexOf("/")) == getEmail()) {
                            var index = c.indexOf("/");
                            var id = c.substring(index + 1, c.indexOf("/", index + 1));
                            if (id == @Model.SiteId) {
                                index = c.indexOf("/", index + 1);
                                var date = c.substring(index, c.indexOf("=", index + 1))
                                if (date = '@Model.Date.ToString("MM-dd-yyyy").Substring(0, @Model.Date.ToString().IndexOf(' ') + 1)') {
                                var columns = c.substring(c.indexOf("=", index + 1) + 1).split(':');
                                for (var j = 0; j < columns.length - 1; j++)
                                    dsSort.push({ field: columns[j] });
                            }
                        }
                    }
                }

                $("#grid").kendoGrid({
                    dataSource: {
                        type: "json",
                        data: data,
                        pageSize: 10,
                        requestEnd: function() {
                            kendo.ui.progress($("#loading"), false);
                        }
                    },
                    dataBound: onDataBound,
                    pageable: {
                        buttonCount: 10
                    },
                    filterable: {
                        mode: "row"
                    },
                    scrollable: true,
                    groupable: true,
                    sortable: true,
                    resizable: true,
                    reorderable: true,
                    allowCopy: true,
                    columns: myColumns
                });

                var kendoGrid = $("#grid").data('kendoGrid');
                kendoGrid.dataSource.group(dsSort);
            }
            else{
                $("#grid").text("No data");
                kendo.ui.progress($("#loading"), false);
            }
            }
        });

        function onDataBound(e) {
            gridDataSource = e.sender.dataSource;
            var group = gridDataSource.group();

            var columns = "";
            $(group).each(function(i, v) {
                columns += v.field.replace(/\s/g, '') + ':';
            });

            var date = new Date();
            date.setTime(date.getTime() + (30 * 24 * 60 * 60 * 1000));
            document.cookie = "grouping " + getEmail() + '/@Model.SiteId/@Model.Date.ToString("MM-dd-yyyy")' + "=" + columns + "; expires=" + date.toGMTString() + "; path=/";
        }

        $(document).on('click', '#export', function() {
            var first = fields.slice(1).join(';');
            var text = [];
            text.push(first + '\n');
            $(values).each(function(index, row) {
                text.push(row.slice(1).join(';') + '\n');
            });

            var file = new Blob(text, { type: 'text/plain' });
            if (navigator.msSaveBlob) { // IE 10+
                navigator.msSaveBlob(file, "Report.csv");
            } else {
                var link = document.createElement("a");
                if (link.download !== undefined) {
                    var url = URL.createObjectURL(file);
                    link.setAttribute("href", url);
                    link.setAttribute("download", "Report.csv");
                    link.style = "visibility:hidden";
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                }
            }
        });
    });
</script>
<style>
    .k-filter-row .k-dropdown-operator {
        right: 0;
    }

    .k-filtercell > span {
        padding-right: 2.8em;
    }
</style>

Detego.CatWalk.Web/Views/StockTakes/Index.cshtml
@{
    ViewBag.Title = "Stocktakes";
}

<h2>Stocktakes</h2>
<div class="box wide">
    <div class="demo-section k-content">
        <div id="treeview"></div>
    </div>
</div>

<script id="combineTemplate" type="text/x-kendo-template">
        <a class="k-button" id="combineButton" href="\#" onclick="return toolbar_click();">Combine</a>
</script>

<script id="itemTemplate" type="text/x-kendo-template">
    # if (item.TenantUnitType == 1) { #
    <span class='itemType'>L</span>
    # } #
    # if (item.TenantUnitType == 2) { #
    <span class='itemType'>P</span>
    # } #
    # if (item.TenantUnitType == 3) { #
    <span class='itemType'>S</span>
    # } #
    # if (item.TenantUnitType == 4) { #
    <span class='itemType'>l</span>
    # } #
    #: item.Name #
    # if (item.TenantUnitType == 3 && item.Address != null) { #
    <span style='margin-left: 100px'>#: getAddress(item.Address) #</span>
    # } #
</script>

<script> 
    var serviceRoot = ApiBaseUrl + "tenants/";
    var tenantDS = new kendo.data.HierarchicalDataSource({
        transport: {
            read: {
                url: serviceRoot,
                dataType: "json"
            }
        },
        schema: {
            model: {
                id: "Id",
                Name: "Name",
                TenantUnitType: "TenantUnitType",
                Address: "Address",
                hasChildren: function(data) {
                    if (data.TenantUnitType == 4) {
                        return false;
                    } else {
                        return true;
                    }
                }
            }
        }
    });

    $("#treeview").kendoTreeView({
        template: kendo.template($("#itemTemplate").html()),
        dataSource: tenantDS,
        dataTextField: "Name",
        select: onSelect
    });

    function onSelect(e) {
        select(e.node);
    }

    function select(node) {
        var dataItem = $('#treeview').data('kendoTreeView').dataItem(node);

        if (dataItem.TenantUnitType == 4) {
            $('#treeview').find("#grid").remove();
            var grid = "<div id='grid' />";
            $(node).find(".k-in:first").after(grid);

            $("#grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: ApiBaseUrl + "stocktakes/" + dataItem.Id,
                            dataType: "json",
                            cache: false
                        }
                    },
                    schema: {
                        model: {
                            id: "Id",
                            fields: {
                                Number: "Number",
                                Start: { type: "date" },
                                First: { type: "date" },
                                Last: { type: "date" },
                                End: { type: "date" },
                                Quantity: { type: "number" }
                            }
                        }
                    },
                    pageSize: 10
                },
                pageable: true,
                sortable: true,
                resizable: true,
                allowCopy: true,
                toolbar: [
                  { template: kendo.template($("#combineTemplate").html()) }
                ],
                columns: [
                    { template: "<input type='checkbox' class='checkbox' />", width: "5%" },
                    { field: "Number", title: "Stocktake", template: '#=makeLink(Id, Number)#', width: "20%" },
                    { field: "First", title: "First Read", type: "date", format: "{0:dd-MM-yyyy HH-mm}", width: "20%" },
                    { field: "Last", title: "Last Read", type: "date", format: "{0:dd-MM-yyyy HH-mm}", width: "20%" },
                    { field: "End", title: "End", type: "date", format: "{0:dd-MM-yyyy HH-mm}", width: "20%" },
                    { field: "Quantity", title: "Actual", width: "15%" }
                ]
            });
        }
        else if (dataItem.TenantUnitType == 3) {
            $('#treeview').find("#grid").remove();
            var grid = "<div id='grid' />";
            $(node).find(".k-in:first").after(grid);

            $("#grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: ApiBaseUrl + "stocktakes/site/" + dataItem.Id,
                            dataType: "json"
                        }
                    },
                    schema: {
                        model: {
                            fields: {
                                Date: { type: "date" },
                                StockTakes: { type: "number" },
                                Quantity: { type: "number" }
                            }
                        }
                    },
                    pageSize: 10
                },
                pageable: true,
                sortable: true,
                resizable: true,
                allowCopy: true,
                columns: [
                    { field: "Date", title: "Date", type: "date", format: "{0:dd-MM-yyyy}", template: '#=makeDateLink(' + dataItem.Id + ', Date)#', width: "50%" },
                    { field: "StockTakes", title: "Stocktakes Count", width: "20%" },
                    { field: "Quantity", title: "Actual", width: "30%" }
                ]
            });
        }

        if (getUserRole() == "User Account") {
            $(".k-grid-content col:first").css("width", "0%")
            $("#combineButton").closest(".k-grid-toolbar").hide();
        }
    }

    function toolbar_click() {
        var combinedItem = null;
        var dataItemsToDelete = [];
        var checkedIds = [];
        var checked = $('#treeview').find("#grid input:checked");
        var grid = $("#grid").data("kendoGrid");
        $(checked).each(function(index) {
            var row = $(checked[index]).closest("tr");
            var dataItem = grid.dataItem(row);
            if (index == 0) {
                combinedItem = dataItem;
            } else {
                dataItemsToDelete.push(dataItem);
            }
            checkedIds.push(dataItem.Id);
        });

        if ($(checked).length == 2) {
            $.ajax({
                url: ApiBaseUrl + "StockTakes",
                type: "POST",
                contentType: 'application/json',
                dataType: "array[integer]",
                data: JSON.stringify(checkedIds),
                success: function(result) {
                    //grid.dataSource.data([]);
                    //grid.dataSource.read();
                    //grid.refresh();
                },
                failure: function() {
                }
            });
            var node = $('#treeview').data('kendoTreeView').select()[0];
            var parent = $('#treeview').data('kendoTreeView').parent(node);
            $('#treeview').data('kendoTreeView').select(parent);
            select(parent);
            alert("Combining may take few minutes. Stocktake information may be incorrect.");
        } else {
            alert("Please selected only two stocktakes to combine.");
        }

        return false;
    }

    function isInArray(value, array) {
        return array.indexOf(value) > -1;
    }

    function makeLink(id, number) {
        var link = '<a href=@Url.Action("Report", "StockTakes")/' + id + '>' + number + '</a>';
        return link;
    }

    function makeDateLink(id, date) {
        temp = moment(date).format('MM-DD-YYYY')
        var link = '<a href=@Url.Action("Report", "StockTakes")/' + id + '/' + temp + '>' + temp + '</a>';
        return link;
    }
</script>
<style>
.k-grid td a {
    color: #00365a;
}
</style>